# Site settings
url: "https://www.mpri.me"
name: 'Marco Primi'
subname: 'a.k.a. mprime'
# Meta
title: "Marco Primi"
description: "Marco Primi's Homepage"

# Links
github_username:  mprimi
linkedin_username: marcoprimi
soundcloud_username:  djallyoucaneat
notes_url: "https://github.com/mprimi/notes"
email: marco@mpri.me
public_key_url: "marco.txt"

# Images
avatar: yes
avatar_img_path: "imgs/avatar.jpg"
front_img: yes
front_img_path: "imgs/background.jpg"
favicon_img: yes
favicon_img_path: "imgs/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty

exclude: ["LICENSE", README.md]
